# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'ZeroWaste' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZeroWaste
  
  # Util
  pod 'Then'
  pod 'CancelBag'
  
  # KakaoLogin
  pod 'KakaoSDK'

  target 'ZeroWasteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZeroWasteUITests' do
    # Pods for testing
  end

end
